default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: mysql

development:
  <<: *default
  database: pai_learning_dev

test:
  <<: *default
  database: pai_learning_test

production:
  <<: *default
  database: <%= ENV['PAI_LEARNING_DATABASE'] %>
  host: <%= ENV['PAI_LEARNING_HOST'] %>
  username: <%= ENV['PAI_LEARNING_USERNAME'] %>
  password: <%= ENV['PAI_LEARNING_PASSWORD'] %>
